### ISSUE TITLE
Update SDK to work with the latest Scala generator

### ISSUE THREAD

**Issue by AttilaMihaly** [finos/morphir-jvm#60]
The main changes are:

- Multiple modules have been moved back into `Basics` to make the structure cleaner and more in-line with elm/core.
- Curried functions have been changed to multi-arg because that works better with the Scala type inferencer.

**Comment by DamianReeves** [comment]
@AttilaMihaly if you can list what are the changes that need to be done here, I can take a shot at applying those changes.

**Comment by AttilaMihaly** [comment]
Sure. I don't think we want to do the currying change for now since it doesn't seem to help the type-inferencer. In terms of the changes needed on the SDK the summary is that we want to align it to `elm/core` as much as possible. To be even more concrete you can use the SDK definition in the IR to see the exact modules and functions. Here's an example for `Basics`:
- https://github.com/finos/morphir-elm/blob/master/src/Morphir/IR/SDK/Basics.elm

**Comment by AttilaMihaly** [comment]
Also, if you get the time to work on this it might be best to avoid breaking changes and instead of moving functions around just add new ones and remove the old ones later.
